package com.woniuxy.domain;
// Generated 2019-8-30 15:11:07 by Hibernate Tools 5.4.2.Final

import java.util.Date;

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer eid;
	private Dept dept;
	private String ename;
	private Double sal;
	private Date hiredate;

	public Emp() {
	}

	public Emp(Dept dept, String ename, Double sal, Date hiredate) {
		this.dept = dept;
		this.ename = ename;
		this.sal = sal;
		this.hiredate = hiredate;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Double getSal() {
		return this.sal;
	}

	public void setSal(Double sal) {
		this.sal = sal;
	}

	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	@Override
	public String toString() {
		return "Emp [eid=" + eid + ", ename=" + ename + ", sal=" + sal + ", hiredate=" + hiredate + "]";
	}
  
	
}
